kind: ConfigMap
apiVersion: v1

metadata:
  name: cloud-observability-platform-configmap

data:
  APP_NAME: {{ .Values.config.appName | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}