apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-observability-platform.fullname" . }}-configmap
  namespace: cop
  labels:
    {{- include "cloud-observability-platform.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}