kind: PersistentVolume
apiVersion: v1
metadata:
  name: cop-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: /mnt/data