kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
    name: cop-pvc
    namespace: cop
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.persistence.size}}
    storageClassName: {{ .Values.persistence.storageClass}}