apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-observability-platform.fullname" . }}
  namespace: cop
  labels:
    {{- include "cloud-observability-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    {{- include "cloud-observability-platform.selectorLabels" . | nindent 4 }}
