apiVersion: v1
kind: Service

metadata:
  name: cloud-observability-platform-service

spec:
  type: {{ .Values.service.type }}

  selector:
    app: cloud-observability-platform

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000