kind: PersistentVolume
apiVersion: v1
metadata:
  name: cop-pv
  namespace: cop
spec:
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data