kind: Service
apiVersion: v1
metadata: 
  name: cop-service
  namespace: cop
spec:
  selector:
    app: cloud-observability-platform
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort